### ISSUE TITLE
Translation into Russian does not work.

### ISSUE THREAD

**Issue by Hubbotu** [dmartinzar/hnmechnaz#11]
He is in English. All descriptions in English = (
https://i.imgur.com/pmwLN6n.jpg

**Comment by dmartinzar** [comment]
I just put out version 12 which should fix the issue. The `ruRU.lua` file was trying to set itself as the default locale, even though the `enUS.lua` file loaded before it was already set as the default. Apparently AceLocale ignores the localization entirely if it tries to override the default.
