### ISSUE TITLE
Nazjatar Treasures (Rares?) Are Phased Until Intro Quests are Done

### ISSUE THREAD

**Issue by Protuhj** [dmartinzar/hnmechnaz#3]
For Alliance, until the player does "A Tempered Blade" (Quest 56156), you can't loot treasures or I'm guessing see any rare spawns. 

For Horde, the quest is "Save a Friend" (Quest 55500)

It's the same quest that unlocks world quests that puts the player in the normal phase.

It would be nice if the addon could hide the treasures and let the player know what they need to do to get them to show.

**Comment by dmartinzar** [comment]
Added in https://github.com/dmartinzar/hnmechnaz/commit/0f55a9b5bfa14e837a7efbedaf2f9d5dc83f35b6
